[package]
name = "speedy"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.29"
ratatui = "0.30"
unicode-segmentation = "1.12"
rustyline = "17.0"
pdf-extract = "0.10.0"
epub = "2.1.5"
arboard = "3.6.1"
thiserror = "2.0.18"
